In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import sys

(parent_folder_path, current_dir) = os.path.split(os.path.abspath(''))
sys.path.append(parent_folder_path)
sys.path.append(os.path.join(parent_folder_path, 'simulator'))
sys.path.append(os.path.join(parent_folder_path, 'equities/data_processing'))

# os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"

import numpy as np
import pandas as pd
import random
from typing import List, Tuple
from copy import deepcopy
from tqdm import tqdm
from glob import glob
from decimal import Decimal

from simulator.core import Message
from simulator.markets.order_book import OrderBook
from simulator.markets.orders import LimitOrder, Side, MarketOrder
from equities.data_processing import itch_preproc
from equities.data_processing import itch_encoding

In [4]:
SYMBOL = "X"
TIME = 0


class FakeExchangeAgent:
    def __init__(self):
        self.messages = []
        self.current_time = TIME
        self.mkt_open = TIME
        self.book_logging = None
        self.stream_history = 10

    def reset(self):
        self.messages = []

    def send_message(self, recipient_id: int, message: Message, _: int = 0):
        self.messages.append((recipient_id, message))

    def logEvent(self, *args, **kwargs):
        pass


def setup_book_with_orders(
    bids: List[Tuple[int, List[int]]] = [], asks: List[Tuple[int, List[int]]] = []
) -> Tuple[OrderBook, FakeExchangeAgent, List[LimitOrder]]:
    agent = FakeExchangeAgent()
    book = OrderBook(agent, SYMBOL)
    orders = []

    for price, quantities in bids:
        for quantity in quantities:
            order = LimitOrder(1, TIME, SYMBOL, quantity, Side.BID, price)
            book.handle_limit_order(order)
            orders.append(order)

    for price, quantities in asks:
        for quantity in quantities:
            order = LimitOrder(1, TIME, SYMBOL, quantity, Side.ASK, price)
            book.handle_limit_order(order)
            orders.append(order)

    agent.reset()

    return book, agent, orders

### Exploring book methods

In [49]:
book, agent, orders = setup_book_with_orders(
    bids=[
        (100, [40, 10]),
        (200, [10, 30, 20, 10]),
    ],
    asks=[
        (300, [10, 50, 20]),
        (400, [40, 10]),
        (500, [20]),
    ],
)

In [15]:
vars(book)

{'owner': <__main__.FakeExchangeAgent at 0x7f3e3c94bb60>,
 'symbol': 'X',
 'bids': [<simulator.markets.price_level.PriceLevel at 0x7f3e3c92eae0>,
 'asks': [<simulator.markets.price_level.PriceLevel at 0x7f3e3c92de50>,
 'last_trade': None,
 'book_log2': [],
 'quotes_seen': set(),
 'history': [{'time': 0,
   'type': 'LIMIT',
   'order_id': 0,
   'agent_id': 1,
   'side': 'BID',
   'quantity': 40,
   'price': 100},
  {'time': 0,
   'type': 'LIMIT',
   'order_id': 1,
   'agent_id': 1,
   'side': 'BID',
   'quantity': 10,
   'price': 100},
  {'time': 0,
   'type': 'LIMIT',
   'order_id': 2,
   'agent_id': 1,
   'side': 'BID',
   'quantity': 10,
   'price': 200},
  {'time': 0,
   'type': 'LIMIT',
   'order_id': 3,
   'agent_id': 1,
   'side': 'BID',
   'quantity': 30,
   'price': 200},
  {'time': 0,
   'type': 'LIMIT',
   'order_id': 4,
   'agent_id': 1,
   'side': 'BID',
   'quantity': 20,
   'price': 200},
  {'time': 0,
   'type': 'LIMIT',
   'order_id': 5,
   'agent_id': 1,
   'side': 'BI

In [16]:
vars(agent)

{'messages': [],
 'current_time': 0,
 'mkt_open': 0,
 'book_logging': None,
 'stream_history': 10}

In [20]:
# ordered by end of bid side book to end of ask side book
orders

[(Agent 1 @ 1970-01-01 00:00:00) : BID 40 X @ $1.00,
 (Agent 1 @ 1970-01-01 00:00:00) : BID 10 X @ $1.00,
 (Agent 1 @ 1970-01-01 00:00:00) : BID 10 X @ $2.00,
 (Agent 1 @ 1970-01-01 00:00:00) : BID 30 X @ $2.00,
 (Agent 1 @ 1970-01-01 00:00:00) : BID 20 X @ $2.00,
 (Agent 1 @ 1970-01-01 00:00:00) : BID 10 X @ $2.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 10 X @ $3.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 50 X @ $3.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 20 X @ $3.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 40 X @ $4.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 10 X @ $4.00,
 (Agent 1 @ 1970-01-01 00:00:00) : ASK 20 X @ $5.00]

In [50]:
print(orders[1])
print(book.get_l3_bid_data())

# Cancel bid order, mid book
book.cancel_order(orders[1])
print(book.get_l3_bid_data())

agent.messages

(Agent 1 @ 1970-01-01 00:00:00) : BID 10 X @ $1.00
[(200, [10, 30, 20, 10]), (100, [40, 10])]
[(200, [10, 30, 20, 10]), (100, [40])]


[(1,
  OrderCancelledMsg(message_id=39, order=(Agent 1 @ 1970-01-01 00:00:00) : BID 10 X @ $1.00))]

In [52]:
# book.pretty_print(silent=False)

In [53]:
print("L1 bid data:", book.get_l1_bid_data()) # best bid tuple (price, volume)
print("L1 ask data:", book.get_l1_ask_data()) # best ask tuple (price, volume)
print("L2 bid data:", book.get_l2_bid_data()) # entire bid side
print("L2 ask data:", book.get_l2_ask_data()) # entire ask side
print("L3 bid data:", book.get_l3_bid_data()) # full order view bid side
print("L3 ask data:", book.get_l3_ask_data()) # full order view ask side

print("transacted volume", book.get_transacted_volume()) # tuple (bid, ask)
print("order book imbalance", book.get_imbalance()) # tuple (volume imbalance value, side that has more volume)

L1 bid data: (200, 70)
L1 ask data: (300, 80)
L2 bid data: [(200, 70), (100, 40)]
L2 ask data: [(300, 80), (400, 50), (500, 20)]
L3 bid data: [(200, [10, 30, 20, 10]), (100, [40])]
L3 ask data: [(300, [10, 50, 20]), (400, [40, 10]), (500, [20])]
transacted volume (0, 0)
order book imbalance (0.2666666666666667, <Side.ASK: 'ASK'>)


In [93]:
# init new book under nasdaq agent
agent = FakeExchangeAgent()
book = OrderBook(agent, SYMBOL)
assert book.bids == book.asks == [] # empty book

# insert bid order
bid_order = LimitOrder(
    agent_id=1,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=10,
    side=Side.BID,
    limit_price=100,
)
book.handle_limit_order(bid_order)

# insert another bid order with id specified
order2 = LimitOrder(
    order_id=69,
    agent_id=1,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=20,
    side=Side.BID,
    limit_price=100,
)
book.handle_limit_order(order2)

# insert ask order
ask_order = LimitOrder(
    agent_id=1,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=20,
    side=Side.ASK,
    limit_price=110,
)
book.handle_limit_order(ask_order)

print("L3 bid data:", book.get_l3_bid_data())
print("L3 ask data:", book.get_l3_ask_data())

print("bid_order.order_id:", agent.messages[0][1].order.order_id)
print("order2.order_id:", agent.messages[1][1].order.order_id)
print("ask_order.order_id:", agent.messages[2][1].order.order_id)

L3 bid data: [(100, [10, 20])]
L3 ask data: [(110, [20])]
bid_order.order_id: 60
order2.order_id: 69
ask_order.order_id: 61


In [94]:
# send buy order that partially consumes one order
market_order = MarketOrder(
    agent_id=2,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=10,
    side=Side.BID,
)
book.handle_market_order(market_order)

print("L3 bid data:", book.get_l3_bid_data())
print("L3 ask data:", book.get_l3_ask_data())
print("transacted volume", book.get_transacted_volume()) # tuple (buy, sell)

L3 bid data: [(100, [10, 20])]
L3 ask data: [(110, [10])]
transacted volume (10, 0)


In [95]:
# Modify order quantity down from 10 to 30
modified_order = deepcopy(bid_order)
modified_order.quantity = 30

book.modify_order(bid_order, modified_order)
print("L3 bid data:", book.get_l3_bid_data()) # order priority is changed
print("L3 ask data:", book.get_l3_ask_data())

L3 bid data: [(100, [20, 30])]
L3 ask data: [(110, [10])]


In [96]:
# place price-to-comply order and then cancel it
order = LimitOrder(
    agent_id=1,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=10,
    side=Side.BID,
    is_price_to_comply=True,
    limit_price=100,
)
book.handle_limit_order(order)
print("(pre-cancel) L3 bid data:", book.get_l3_bid_data())
print("(pre-cancel) L3 ask data:", book.get_l3_ask_data())

book.cancel_order(order)
print("(post-cancel) L3 bid data:", book.get_l3_bid_data())
print("(post-cancel) L3 ask data:", book.get_l3_ask_data())

(pre-cancel) L3 bid data: [(101, []), (100, [20, 30, 10])]
(pre-cancel) L3 ask data: [(110, [10])]
(post-cancel) L3 bid data: [(100, [20, 30])]
(post-cancel) L3 ask data: [(110, [10])]


In [97]:
# Replace 10 @ $110 with 50 @ $111, ask side of book
new_ask_order = LimitOrder(
    agent_id=1,
    time_placed=TIME,
    symbol=SYMBOL,
    quantity=50,
    side=Side.ASK,
    limit_price=111,
)

book.replace_order(1, ask_order, new_ask_order) # first arg is agent_id
print("L3 bid data:", book.get_l3_bid_data())
print("L3 ask data:", book.get_l3_ask_data())
print("old_order.order_id:", agent.messages[-1][1].old_order.order_id)
print("new_order.order_id:", agent.messages[-1][1].new_order.order_id)

L3 bid data: [(100, [20, 30])]
L3 ask data: [(111, [50])]
old_order.order_id: 61
new_order.order_id: 64


### Working with real data

In [5]:
# define load paths
raw_itch_load_path = parent_folder_path + '/dataset/raw/ITCH/'
processed_dataset = '03272019.NASDAQ_ITCH50_AAPL_message_proc.npy'
proc_data_dir = os.path.join('dataset/proc/ITCH/full_view/', processed_dataset)
proc_data_dir = parent_folder_path + '/' + proc_data_dir
symbols_load_path = parent_folder_path + '/dataset/symbols/'
symbols_file = sorted(glob(symbols_load_path + '*sp500*.txt'))[0]

# locate raw ITCH data
itch_message_files = sorted(glob(raw_itch_load_path + '*message*.csv'))
itch_book_files = sorted(glob(raw_itch_load_path + '*book*.csv'))
print('found', len(itch_message_files), 'ITCH message files')
print('found', len(itch_book_files), 'ITCH book files')

# create reverse ticker symbol mapping (key is index, value is ticker)
# print(symbols_file)
tickers = {}
with open(symbols_file) as f:
    idx = 0
    for line in f:
        idx += 1
        # tickers[line.strip()] = idx
        tickers[idx] = line.strip()
# print("Number of unique symbols:", len(tickers))

# load raw ITCH data (book)
symbols = []
for m_f, b_f in tqdm(zip(itch_message_files, itch_book_files)):
    if '03272019' not in m_f:
        continue
    # print(m_f)
    print(b_f)
    
    itch_messages = itch_preproc.load_message_df(m_f)

    itch_book = pd.read_csv(
        b_f,
        # index_col=False,
        # header=None
    )
    assert len(itch_messages) == len(itch_book)

    # remove disallowed order types
    allowed_events=['A','E','C','D','R']
    itch_messages = itch_messages.loc[itch_messages.type.isin(allowed_events)]
    # make sure book is same length as messages
    itch_book = itch_book.loc[itch_messages.index]

    # print("ITCH messages shape:", itch_messages.shape)
    print("ITCH book shape:", itch_book.shape)

    # # remove time field from ITCH book data
    # itch_book = itch_book.drop(columns=['time'])

    # symbol to store in list and use to create OB objects in loop later
    symbol = m_f.rsplit('/', maxsplit=1)[-1][:-12].rsplit('_', maxsplit=1)[-1]
    print("Adding symbol:", symbol)
    symbols.append(symbol)

# load processed ITCH data (messages)
proc_messages = np.array(np.load(proc_data_dir, mmap_mode='r'))
assert len(itch_book) == len(proc_messages) + 1 # off by 1 bc of first message
print("proc_messages.shape:", proc_messages.shape)
print("proc_messages:", proc_messages)
print([ "ticker", "order_id",
        "event_type", "direction", "price_abs", "price", "fill_size", "remain_size",
        "delta_t_s", "delta_t_ns", "time_s", "time_ns", "old_id",
        "price_ref", "fill_size_ref", "time_s_ref", "time_ns_ref", "old_price_abs"])

found 8 ITCH message files
found 8 ITCH book files


0it [00:00, ?it/s]

/home/aaron/Documents/Github/MarketSimT/dataset/raw/ITCH/03272019.NASDAQ_ITCH50_AAPL_book_20.csv


8it [00:04,  1.69it/s]

ITCH book shape: (2003141, 81)
Adding symbol: AAPL
proc_messages.shape: (2003140, 18)
proc_messages: [[       40     15969         1 ...     -9999     -9999     -9999]
 [       40     20677         1 ...     -9999     -9999     -9999]
 [       40     22061         1 ...     -9999     -9999     -9999]
 ...
 [       40 335312241         4 ...     56890 566837429     -9999]
 [       40 343725045         4 ...     57309 388685794     -9999]
 [       40 353209329         4 ...     57799 533545153     -9999]]
['ticker', 'order_id', 'event_type', 'direction', 'price_abs', 'price', 'fill_size', 'remain_size', 'delta_t_s', 'delta_t_ns', 'time_s', 'time_ns', 'old_id', 'price_ref', 'fill_size_ref', 'time_s_ref', 'time_ns_ref', 'old_price_abs']


In [6]:
itch_book

time  1_bid_price  1_bid_vol  1_ask_price  1_ask_vol  \
0        14400006432545          NaN        NaN       207.85       18.0   
1        14400008777412       129.33      100.0       207.85       18.0   
2        14400016498868       129.33      100.0       207.85       18.0   
3        14400017857990       129.33      100.0       207.85       18.0   
4        14403597489791       129.33      100.0       192.70      300.0   
...                 ...          ...        ...          ...        ...   
2010131  72000073334596       188.00        1.0       188.99     1000.0   
2010132  72000073447563       175.00       50.0       188.99     1000.0   
2010133  72000073477970          NaN        NaN       188.99     1000.0   
2010134  72000074023439          NaN        NaN       188.99     1000.0   
2010135  72000074213874          NaN        NaN          NaN        NaN   

         2_bid_price  2_bid_vol  2_ask_price  2_ask_vol  3_bid_price  ...  \
0                NaN        NaN          NaN        NaN          NaN  ...   
1                NaN        NaN          NaN        NaN          NaN  ...   
2             114.94        1.0          NaN        NaN          NaN  ...   
3             114.94        1.0          NaN        NaN        98.39  ...   
4             114.94        1.0       207.85       18.0        98.39  ...   
...              ...        ...          ...        ...          ...  ...   
2010131       175.00       50.0       195.00     2600.0          NaN  ...   
2010132          NaN        NaN       195.00     2600.0          NaN  ...   
2010133          NaN        NaN       195.00     2600.0          NaN  ...   
2010134          NaN        NaN          NaN        NaN          NaN  ...   
2010135          NaN        NaN          NaN        NaN          NaN  ...   

         18_ask_price  18_ask_vol  19_bid_price  19_bid_vol  19_ask_price  \
0                 NaN         NaN           NaN         NaN           NaN   
1                 NaN         NaN           NaN         NaN           NaN   
2                 NaN         NaN           NaN         NaN           NaN   
3                 NaN         NaN           NaN         NaN           NaN   
4                 NaN         NaN           NaN         NaN           NaN   
...               ...         ...           ...         ...           ...   
2010131           NaN         NaN           NaN         NaN           NaN   
2010132           NaN         NaN           NaN         NaN           NaN   
2010133           NaN         NaN           NaN         NaN           NaN   
2010134           NaN         NaN           NaN         NaN           NaN   
2010135           NaN         NaN           NaN         NaN           NaN   

         19_ask_vol  20_bid_price  20_bid_vol  20_ask_price  20_ask_vol  
0               NaN           NaN         NaN           NaN         NaN  
1               NaN           NaN         NaN           NaN         NaN  
2               NaN           NaN         NaN           NaN         NaN  
3               NaN           NaN         NaN           NaN         NaN  
4               NaN           NaN         NaN           NaN         NaN  
...             ...           ...         ...           ...         ...  
2010131         NaN           NaN         NaN           NaN         NaN  
2010132         NaN           NaN         NaN           NaN         NaN  
2010133         NaN           NaN         NaN           NaN         NaN  
2010134         NaN           NaN         NaN           NaN         NaN  
2010135         NaN           NaN         NaN           NaN         NaN  

[2003141 rows x 81 columns]

In [7]:
proc_messages[0:10]

array([[       40,     15969,         1,         0,     12933,       999,
              100,     -9999,         0,   2344867,     14400,   8777412,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     20677,         1,         0,     11494,      -999,
                1,     -9999,         0,   7721456,     14400,  16498868,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     22061,         1,         0,      9839,      -999,
                1,     -9999,         0,   1359122,     14400,  17857990,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     98453,         1,         1,     19270,       999,
              300,     -9999,         3, 579631801,     14403, 597489791,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     99329,         1,         1,     21490,       999,
               85,     -9999,     

In [8]:
print("Number of unique symbols:", len(tickers))
print(tickers[proc_messages[0][0]])
symbols

Number of unique symbols: 503
AAPL


['AAPL']

In [48]:
# def merge_lists(list1, list2):
#     '''Merge two lists into one by alternating elements from each list.'''
#     list = []
#     for item1, item2 in zip(list1, list2):
#         list.append(item1)
#         list.append(item2)
#     return list

def validate_book(sim_book, actual_book, book_idx, n_levels=20):
    # pad and format simulated data
    sim_bids = sim_book.get_l2_bid_data()
    sim_bids += [(0,0)] * (n_levels - len(sim_bids))
    sim_asks = sim_book.get_l2_ask_data()
    sim_asks += [(0,0)] * (n_levels - len(sim_asks))
    sim_book = merge_lists(sim_bids, sim_asks)

    # format actual data
    b_prices = actual_book.iloc[book_idx, 1::2].mul(100).fillna(0).astype(int).values # bid and ask prices
    b_vol = actual_book.iloc[book_idx, 2::2].fillna(0).astype(int).values # bid and ask volumes
    actual_book = list(zip(b_prices, b_vol))

    # compare
    # print(sim_book)
    # print(actual_book)
    assert sim_book == actual_book, f"Book {book_idx} not validated. Simulated book: {sim_book}, Actual book: {actual_book}"
    # print(f"Book {book_idx} validated.")


In [72]:
# init new book under nasdaq agent
nasdaq_agent = FakeExchangeAgent()

# create a dictionary of order books based on each symbol in symbols
order_books = {}
for symbol in symbols:
    order_books[symbol] = OrderBook(nasdaq_agent, symbol)

# empty book
assert order_books[tickers[proc_messages[0][0]]].bids == order_books[tickers[proc_messages[0][0]]].asks == []


In [73]:
# first message is missing in proc_messages, so we'll use the raw message file to start the book
first_message = itch_messages.iloc[0]
print(first_message)

# insert bid order
bid_order = LimitOrder(
    order_id=first_message['id'],
    agent_id=1, # world agent, leave alone for now
    time_placed=first_message['time'],
    symbol=symbols[0],
    quantity=int(first_message['size']),
    side=Side.BID if first_message['side'] == 0 else Side.ASK,
    limit_price=int(first_message['price']*100),
)
order_books[symbols[0]].handle_limit_order(bid_order)

print("L3 bid data:", order_books[symbols[0]].get_l3_bid_data())
print("L3 ask data:", order_books[symbols[0]].get_l3_ask_data())
nasdaq_agent.messages

time        14400006432545
type                     A
id                   13301
side                     1
size                  18.0
price               207.85
cancSize               NaN
execSize               NaN
oldId                  NaN
oldSize                NaN
oldPrice               NaN
mpid                   NaN
Name: 0, dtype: object
L3 bid data: []
L3 ask data: [(20785, [18])]


[(1,
  OrderAcceptedMsg(message_id=81, order=(Agent 1 @ 1970-01-01 04:00:00) : ASK 18 AAPL @ $207.85))]

In [74]:
sample_msgs = proc_messages[0:10]
sample_msgs

array([[       40,     15969,         1,         0,     12933,       999,
              100,     -9999,         0,   2344867,     14400,   8777412,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     20677,         1,         0,     11494,      -999,
                1,     -9999,         0,   7721456,     14400,  16498868,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     22061,         1,         0,      9839,      -999,
                1,     -9999,         0,   1359122,     14400,  17857990,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     98453,         1,         1,     19270,       999,
              300,     -9999,         3, 579631801,     14403, 597489791,
            -9999,     -9999,     -9999,     -9999,     -9999,     -9999],
       [       40,     99329,         1,         1,     21490,       999,
               85,     -9999,     

In [75]:
# [ "ticker", "order_id",
# "event_type", "direction", "price_abs", "price", "fill_size", "remain_size",
# "delta_t_s", "delta_t_ns", "time_s", "time_ns", "old_id",
# "price_ref", "fill_size_ref", "time_s_ref", "time_ns_ref", "old_price_abs"]

# bid_order = LimitOrder(
#     order_id=first_message['id'],
#     agent_id=1, # world agent, leave alone for now
#     time_placed=first_message['time'],
#     symbol=symbols[0],
#     quantity=int(first_message['size']),
#     side=Side.BID if first_message['side'] == 0 else Side.ASK,
#     limit_price=int(first_message['price']*100),
# )

# init variables to keep track of previous time and price
prev_time = first_message['time']
prev_price = int(first_message['price']*100)
book_idx = 1 # start at 1 because we already handled the first message

# iterate through messages and update order books
# for msg in sample_msgs:
for msg in proc_messages:
    print(msg)
    symbol = tickers[msg[0]]
    print("Symbol:", symbol)
    order_id = msg[1]
    print("Order ID:", order_id)
    event_type = msg[2]
    print("Event Type:", event_type)
    direction = Side.BID if msg[3] == 0 else Side.ASK
    print("Direction:", direction)
    if abs(msg[5]) < 999: # if price was not truncated or NaN
        # price = msg[5] + prev_price
        # calculate reference price (previous mid price)
        mid_price = (((itch_book.iloc[book_idx, 1] * 100) + (itch_book.iloc[book_idx, 3] * 100)) / 2) // 1
        price = int(mid_price) + msg[5]
    else: # use price_abs
        price = msg[4]
    print("Price:", price)
    # verify time correctness
    assert prev_time + (msg[8]*1000000000) + msg[9] == (msg[10] * 1000000000) + msg[11]
    time = prev_time + (msg[8]*1000000000) + msg[9]
    print("Time:", time)

    # handle order based on event type
    if event_type == 1:
        # ADD LIMIT ORDER
        fill_size = msg[6]
        print("Fill Size:", fill_size)
        order = LimitOrder(
            order_id=order_id,
            agent_id=1, # world agent, leave alone for now
            time_placed=time,
            symbol=symbol,
            quantity=fill_size,
            side=direction,
            limit_price=price,
        )
        order_books[symbol].handle_limit_order(order)
    else:
        raise NotImplementedError("Event type not implemented")
    
    # compare simulated order book with actual order book
    assert int(itch_book.iloc[book_idx].time) == time, f"Time mismatch: {int(itch_book.iloc[book_idx].time)} != {time}"
    validate_book(order_books[symbol], itch_book, book_idx)
    book_idx += 1

    # update previous time and price
    prev_time = time
    prev_price = price
    

[     40   15969       1       0   12933     999     100   -9999       0
 2344867   14400 8777412   -9999   -9999   -9999   -9999   -9999   -9999]
Symbol: AAPL
Order ID: 15969
Event Type: 1
Direction: Side.BID
Price: 12933
Time: 14400008777412
Fill Size: 100
[      40    20677        1        0    11494     -999        1    -9999
        0  7721456    14400 16498868    -9999    -9999    -9999    -9999
    -9999    -9999]
Symbol: AAPL
Order ID: 20677
Event Type: 1
Direction: Side.BID
Price: 11494
Time: 14400016498868
Fill Size: 1
[      40    22061        1        0     9839     -999        1    -9999
        0  1359122    14400 17857990    -9999    -9999    -9999    -9999
    -9999    -9999]
Symbol: AAPL
Order ID: 22061
Event Type: 1
Direction: Side.BID
Price: 9839
Time: 14400017857990
Fill Size: 1
[       40     98453         1         1     19270       999       300
     -9999         3 579631801     14403 597489791     -9999     -9999
     -9999     -9999     -9999     -9999]
Symbol

NotImplementedError: Event type not implemented

In [66]:
itch_book

time  1_bid_price  1_bid_vol  1_ask_price  1_ask_vol  \
0        14400006432545          NaN        NaN       207.85       18.0   
1        14400008777412       129.33      100.0       207.85       18.0   
2        14400016498868       129.33      100.0       207.85       18.0   
3        14400017857990       129.33      100.0       207.85       18.0   
4        14403597489791       129.33      100.0       192.70      300.0   
...                 ...          ...        ...          ...        ...   
2010131  72000073334596       188.00        1.0       188.99     1000.0   
2010132  72000073447563       175.00       50.0       188.99     1000.0   
2010133  72000073477970          NaN        NaN       188.99     1000.0   
2010134  72000074023439          NaN        NaN       188.99     1000.0   
2010135  72000074213874          NaN        NaN          NaN        NaN   

         2_bid_price  2_bid_vol  2_ask_price  2_ask_vol  3_bid_price  ...  \
0                NaN        NaN          NaN        NaN          NaN  ...   
1                NaN        NaN          NaN        NaN          NaN  ...   
2             114.94        1.0          NaN        NaN          NaN  ...   
3             114.94        1.0          NaN        NaN        98.39  ...   
4             114.94        1.0       207.85       18.0        98.39  ...   
...              ...        ...          ...        ...          ...  ...   
2010131       175.00       50.0       195.00     2600.0          NaN  ...   
2010132          NaN        NaN       195.00     2600.0          NaN  ...   
2010133          NaN        NaN       195.00     2600.0          NaN  ...   
2010134          NaN        NaN          NaN        NaN          NaN  ...   
2010135          NaN        NaN          NaN        NaN          NaN  ...   

         18_ask_price  18_ask_vol  19_bid_price  19_bid_vol  19_ask_price  \
0                 NaN         NaN           NaN         NaN           NaN   
1                 NaN         NaN           NaN         NaN           NaN   
2                 NaN         NaN           NaN         NaN           NaN   
3                 NaN         NaN           NaN         NaN           NaN   
4                 NaN         NaN           NaN         NaN           NaN   
...               ...         ...           ...         ...           ...   
2010131           NaN         NaN           NaN         NaN           NaN   
2010132           NaN         NaN           NaN         NaN           NaN   
2010133           NaN         NaN           NaN         NaN           NaN   
2010134           NaN         NaN           NaN         NaN           NaN   
2010135           NaN         NaN           NaN         NaN           NaN   

         19_ask_vol  20_bid_price  20_bid_vol  20_ask_price  20_ask_vol  
0               NaN           NaN         NaN           NaN         NaN  
1               NaN           NaN         NaN           NaN         NaN  
2               NaN           NaN         NaN           NaN         NaN  
3               NaN           NaN         NaN           NaN         NaN  
4               NaN           NaN         NaN           NaN         NaN  
...             ...           ...         ...           ...         ...  
2010131         NaN           NaN         NaN           NaN         NaN  
2010132         NaN           NaN         NaN           NaN         NaN  
2010133         NaN           NaN         NaN           NaN         NaN  
2010134         NaN           NaN         NaN           NaN         NaN  
2010135         NaN           NaN         NaN           NaN         NaN  

[2003141 rows x 81 columns]

In [13]:
print("L3 bid data:", order_books[symbols[0]].get_l3_bid_data())
print("L3 ask data:", order_books[symbols[0]].get_l3_ask_data())
nasdaq_agent.messages

L3 bid data: [(18573, [25]), (16700, [15]), (15500, [12]), (12933, [100]), (11494, [1]), (9839, [1])]
L3 ask data: [(19270, [300]), (20785, [18]), (21490, [85]), (22500, [150, 5])]


[(1,
  OrderAcceptedMsg(message_id=1, order=(Agent 1 @ 1970-01-01 04:00:00) : ASK 18 AAPL @ $207.85)),
 (1,
  OrderAcceptedMsg(message_id=2, order=(Agent 1 @ 1970-01-01 04:00:00) : BID 100 AAPL @ $129.33)),
 (1,
  OrderAcceptedMsg(message_id=3, order=(Agent 1 @ 1970-01-01 04:00:00) : BID 1 AAPL @ $114.94)),
 (1,
  OrderAcceptedMsg(message_id=4, order=(Agent 1 @ 1970-01-01 04:00:00) : BID 1 AAPL @ $98.39)),
 (1,
  OrderAcceptedMsg(message_id=5, order=(Agent 1 @ 1970-01-01 04:00:03) : ASK 300 AAPL @ $192.70)),
 (1,
  OrderAcceptedMsg(message_id=6, order=(Agent 1 @ 1970-01-01 04:00:03) : ASK 85 AAPL @ $214.90)),
 (1,
  OrderAcceptedMsg(message_id=7, order=(Agent 1 @ 1970-01-01 04:00:03) : ASK 150 AAPL @ $225.00)),
 (1,
  OrderAcceptedMsg(message_id=8, order=(Agent 1 @ 1970-01-01 04:00:03) : ASK 5 AAPL @ $225.00)),
 (1,
  OrderAcceptedMsg(message_id=9, order=(Agent 1 @ 1970-01-01 04:00:05) : BID 25 AAPL @ $185.73)),
 (1,
  OrderAcceptedMsg(message_id=10, order=(Agent 1 @ 1970-01-01 04:00:1

In [14]:
# nasdaq_agent.messages[1][1].order.time_placed

assert int(itch_book.iloc[10].time) == time

itch_book.iloc[10]

time            1.441008e+13
1_bid_price     1.857300e+02
1_bid_vol       2.500000e+01
1_ask_price     1.927000e+02
1_ask_vol       3.000000e+02
                    ...     
19_ask_vol               NaN
20_bid_price             NaN
20_bid_vol               NaN
20_ask_price             NaN
20_ask_vol               NaN
Name: 10, Length: 81, dtype: float64

In [23]:
def merge_lists(list1, list2):
    '''Merge two lists into one by alternating elements from each list.'''
    list = []
    for item1, item2 in zip(list1, list2):
        list.append(item1)
        list.append(item2)
    return list

n_levels = 20
# order_books[symbols[0]].get_L2_snapshots(20)
sim_bids = order_books[symbols[0]].get_l2_bid_data()
sim_bids += [(0,0)] * (n_levels - len(sim_bids))
sim_asks = order_books[symbols[0]].get_l2_ask_data()
sim_asks += [(0,0)] * (n_levels - len(sim_asks))
print(sim_bids)
print(sim_asks)

sim_book = merge_lists(sim_bids, sim_asks)
sim_book


[(18573, 25), (16700, 15), (15500, 12), (12933, 100), (11494, 1), (9839, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]
[(19270, 300), (20785, 18), (21490, 85), (22500, 155), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]


[(18573, 25),
 (19270, 300),
 (16700, 15),
 (20785, 18),
 (15500, 12),
 (21490, 85),
 (12933, 100),
 (22500, 155),
 (11494, 1),
 (0, 0),
 (9839, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0)]

In [15]:
book_idx = 10

b_prices = itch_book.iloc[book_idx, 1::2].mul(100).fillna(0).astype(int).values # bid and ask prices
b_vol = itch_book.iloc[book_idx, 2::2].fillna(0).astype(int).values # bid and ask volumes

# list of tuples [(bid price, bid volume), (ask price, ask volume), ...]
actual_book = list(zip(b_prices, b_vol))
actual_book

[(18573, 25),
 (19270, 300),
 (16700, 15),
 (20785, 18),
 (15500, 12),
 (21490, 85),
 (12933, 100),
 (22500, 155),
 (11494, 1),
 (0, 0),
 (9839, 1),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 0)]

In [24]:
sim_book == actual_book

True